version: "2.1"
volumes:
  myst-data:
services:
  myst:
    build: ./myst
    command: 'service --agreed-terms-and-conditions'
    dns:
      - 1.1.1.1
      - 8.8.8.8
    privileged: true
    restart: always
    network_mode: host
    volumes:
      - "myst-data:/var/lib/mysterium-node"
    labels:
      io.balena.features.kernel-modules: '1'
